### ISSUE TITLE
Reaction conditions

### ISSUE THREAD

**Issue by StephanM87** [Strenda-biocatalysis/Strenda-biocatalysis#19]
Add conditions based on the length of the reaction vessel (for example in a plug flow reactor)

**Comment by KatrinRosenthal** [comment]
1: One might think by the terms used that the flow reactors are not well mixed, but this need not be the case. Therefore, a better name for the first case would be _vessel reactor_.

**Comment by KatrinRosenthal** [comment]
2: I agree. Event-based is a time-dependent case and can be described as dynamic.

**Comment by StephanM87** [comment]
I think this topic should be reviewed once more, I will put this issue into the discussion line for the next meeting

**Comment by StephanM87** [comment]
- We omitted the term well mixed for the flow reactors
- In the future, we will omit the Well mixed definition completely in the flow reactors and stirred tank reactors etc.
