### ISSUE TITLE
Multiphase system: Ratio of the phases

### ISSUE THREAD

**Issue by StephanM87** [Strenda-biocatalysis/Strenda-biocatalysis#22]
We should add the phase ratio as volumes of the phases

**Comment by PeterHalling** [comment]
Probably a more general issue, but fits under this heading. I think we need to be very careful about the use of the word phase, which should be reserved for a very specific meaning. In particular I would avoid the word for something added to the reaction mixture (i.e. as an alternative to "addition" which I suggested, although I think there is probably another better word). I might add a wet biocatalyst preparation - which actually consists of at least 2 phases, a solid and liquid water. I might then add an organic liquid. The system will definitely be multi-phase, but physico-chemical behaviour, not me, will control whether the water mixes completely (so giving a solid-liquid 2 phase system) or remains as a separate phase (so we have a solid and two liquid phases). In general the number, volumes and composition of phases in the reaction mixture will be a result of the experiment, not metadata about how the system was set up. This result may not be known, but we could invite experimenters to report observations on the subject. What must be reported are the various items added to the reaction mixture - but please don't call them phases.

**Comment by PeterHalling** [comment]
Yes, of course.

**Comment by StephanM87** [comment]
# In Group meeting

- Do not define the phases, but concentrate on the relative quantities of what was added
- There is an important difference to measurement and metadata
- Restructure the reaction condition section @PeterHalling 
- Find names for the _compounds_ or _phases_ that were added to the reaction

❗  We now describe the _initial situation_ of the reaction mixture

❗ This discussion confronts the sampling, because here were need to know if it is a single or multiphase system

**Comment by PeterHalling** [comment]
I think we agreed in the meeting (30/5) to avoid the word "phase" for something added in making up the reaction mixture - but instead reserve it for its accepted meaning of something present in the system after everything has been combined. I might add in a solution, and solid particles of a reactant. But physical chemistry, not me, will decide whether it all dissolves to make a single liquid pahse, or wehther some remains as suspended solid. And the composition of the liquid phase in the reaction mixture will probably be significantly different from that of the solution I put in.
However, under Reaction Conditions we still ask people to state the number of phases and give information about each. If information is available about this, it will be from measurements on the reaction mixture (rarely done), and hence a result (so data, not metadata). What the experimenter must know, and can be asked to record, is what they put in to the system. This might be some liquids(s), some solid(s), some gas(es). Some things added may be more than one phase already - for example a wet biocatalyst will probbaly have a solid phase and some adhering liquid. But we must use a word other than phase to refer to these things added in making up the system.
