### ISSUE TITLE
STRENDA biocatalysis paper outline

### ISSUE THREAD

**Issue by StephanM87** [Strenda-biocatalysis/Strenda-biocatalysis#33]
## Link to manuscript: https://github.com/StephanM87/STRENDA-biocatalysis_paper

- Strenda biocatalysis is a metadata standard for biocatalysis, developed by the example of STRENDA
- Key Selling points:
- - __Motivation__: RDM implementation, reproducibility crisis, language issues --> different syntax in the communities
- - __Motivation__: Connect the standardised metadata with the measurement data --> Connect research to data science
- - __Motivation__: We want to reach out to specialists to provide us with expertise
- - Metadata standards defined by international specialists (STRENDA, ESAB, Gardossi paper) and biochemical engineering
- - Modular and interactive due to GitHub
- - Reactive (experimenters from the whole community can propose changes
- - sdRDM implementation for communication between experimenters and software engineers
- - Ask journals to implement these guidelines

- Add an SI with some examples

**Comment by rgiessmann** [comment]
requirement for publication: open access

**Comment by rgiessmann** [comment]
bulletpoint:

* ask other researchers to contribute / become active in the community

**Comment by StephanM87** [comment]
- Status with Nature catalysis --> Dörte
- Implement Examples and the Markdown catalogue into a PDF attachment
-

**Comment by StephanM87** [comment]
Hello, there is a issue with the authentification in Overleaf. I am sorry for that, I will create a google google document and send it to you
