### ISSUE TITLE
pH measurement

### ISSUE THREAD

**Issue by PeterHalling** [Strenda-biocatalysis/Strenda-biocatalysis#35]
Some thoughts in advance of discussions on Friday.

The ideal is that pH is measured in the actual reaction mixture around the biocatalyst. However, there are often good reasons why this is impossible or difficult. And if the reaction mixture does not include a dilute aqueous solution phase, there will often be no defined pH scale that can be used anyway. Measurements of pH at other stages do allow the experiment to be reproduced, provided necessary details are absolutely clear. It is essential to specify exactly what has been added in the solution or dispersion in which pH is measured and/or adjusted. In a single-phase reaction mixture, this may mean just some of the ingredients – others may be added after pH measurement, for example a miscible co-solvent. If the final reaction mixture is multi-phase, pH might be measured in a solution that is then combined with other additions. 

The temperature of the solution/dispersion at the point of pH measurement must be recorded, particularly if this is far from the temperature at which the electrode is calibrated. 

Normally the pH electrode will be calibrated in dilute aqueous solution at 20 to 25 oC using standard buffers. If the measurement is not made in a dilute aqueous solution at similar temperature, the pH obtained will only be an apparent value, but the experiment is reproducible provided all necessary detail is given (see above). Occasionally the pH electrode may be calibrated to a recognised pH scale in a different medium (e.g. certain ethanol/water mixtures, some concentrated salt solutions).

**Comment by DomMSNR** [comment]
Thank you for your input. You brought up really good points about determining the pH value that should definitely be considered. 
I have tried to incorporate the following points into the catalog:

- Exact information about when the pH value was measured. E.g. before or after addition of all components of the reaction solution. Or before, during after the reaction....

- Temperature at the time of the pH measurement

- Consideration of the calibration of the pH electrode (if applicable).

Please let me know if you have any further comments.
