### ISSUE TITLE
Figure for the STRENDA biocatalysis guidelines comment to be published in Nature Catalysis

### ISSUE THREAD

**Issue by DomMSNR** [Strenda-biocatalysis/Strenda-biocatalysis#40]
I have been thinking about the figure discussed in our meetings for the Comment to be published in Nature Catalysis. This is a first version of me. I look forward to receiving feedback and suggestions for improvement.

<img src="https://github.com/StephanM87/Strenda-biocatalysis/assets/106530250/9d497b43-7669-487b-a6f5-de5d1cc076aa" width="600">

**Comment by rolandwohlgemuth** [comment]
thank you for your EMails regarding the figure. I think the figure would be suitable for illustrating the interactions of the different communities within the text. I agree that for a figure characterizing the whole comment we need to integrate our overall aims and data exchange. The overall complexity should however be simplified as much as possible in the figure, for example by just using the symbols for the root elements and illustrate data exchange along a biocatalysis workflow. An important element for data exchange is also the ata containing all the results.

**Comment by Peacock68** [comment]
Is there an open graphics file available that allows us to play around with the elements and even remove what is not appropriate?

**Comment by DomMSNR** [comment]
Unfortunately, I do not know how to provide an editable data format for the SVG ('scalable vector graphic') that I have designed, so that everyone is able to change the current design as they want.
 I could upload the SVG file myself, but a program for designing vector graphics (such as Inkscape or GIMP) is required.
