### ISSUE TITLE
Introduction to make clear not all attributes essential

### ISSUE THREAD

**Issue by PeterHalling** [Strenda-biocatalysis/Strenda-biocatalysis#41]
I think it would be good to have a statement early in the introduction, so readers don't think we are asking for all these attributes for every biocatalysis experiment. Something like: "Of course not all attributes will be required to describe any given experiment in biocatalysis. We will in future need decision trees indicating which are needed in any case, but the initial aim is to compile a comprehensive list of all attributes."

**Comment by DomMSNR** [comment]
You're right. It is important to know that not all metadata is necessarily valid for every experiment and therefore not all metadata have to be taken into account when describing a particular experiment.

I'll work that out.

**Comment by Peacock68** [comment]
Thanks for the suggestion. I will take this aspect in account for our manuscript.
